services:
  # Backend API Service
  - type: web
    name: budget-tracker-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://bhargavkatkam0_db_user:Bhargavk%401104@budget-tracker-prod.fd2ctnp.mongodb.net/
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://budget-tracker-react-native-kjff.onrender.com
      - key: EMAIL_USER
        value: thakurkakashi@gmail.com
      - key: EMAIL_PASS
        value: xwvg ekaz yvnu vbcl
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: Budget Tracker <onboarding@resend.dev>
    healthCheckPath: /health
    autoDeploy: true
